version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t jossydee1/node-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push jossydee1/node-app:$version

  test:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      # Install dependencies
      - run: npm install
      #  Run unit tests
      - run: npm test

  deploy_to_eks:
    docker:
      - image: cimg/node:20.3.1

    steps:
      - checkout

      # Configure AWS CLI
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1

      # Authenticate with EKS Cluster
      - run:
          name: Authenticate with EKS Cluster
          command: |
            aws eks --region us-east-1 update-kubeconfig --name NodeApp
      # Deploy to EKS Cluster
      - run:
          name: Deploy to EKS Cluster
          command: |
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml

workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - test:
          requires:
            - build_and_push
      - deploy_to_eks:
          requires:
            - build_and_push
