version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t jossydee1/node-app-vpd:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push jossydee1/node-app-vpd:$version

  unit_test:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      # Install dependencies
      - run: npm install
      #  Run unit test
      - run: npm test

  # deploy_to_eks:
  #   docker:
  #     - image: cimg/node:20.3.1

  #   steps:
  #     - checkout

  #     # Install kubectl
  #     - run:
  #         name: Install kubectl
  #         command: |
  #           sudo curl --silent --location -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl --location --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  #           sudo chmod +x /usr/local/bin/kubectl

  #     # Verify kubectl version
  #     - run:
  #         name: Verify kubectl version
  #         command: kubectl version --short --client

  #     # Install AWS CLI
  #     - run:
  #         name: Install AWS CLI
  #         command: |
  #           sudo apt-get update && sudo apt-get install -y awscli
  #     # Verify AWS CLI Path
  #     - run:
  #         name: Verify AWS CLI Path
  #         command: which aws

  #     # Configure AWS CLI
  #     - run:
  #         name: Configure AWS CLI
  #         command: |
  #           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  #           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  #           aws configure set default.region us-east-1

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/jossydee1/vpd-money_Kube_manifest
            git config --global user.email "jossydee1@gmail.com"
            git config --global user.name "jossydee1"
            pwd
            cd vpd-money_Kube_manifest
            pwd
            echo $TAG
            sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
            cat manifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/jossydee1/vpd-money_Kube_manifest.git main

      # # Install kubectl
      # - run:
      #     name: Install kubectl
      #     command: sudo curl --silent --location -o /usr/local/bin/kubectl "https://amazon-eks.s3.us-east-1.amazonaws.com/1.23.7/2022-01-31/bin/linux/amd64/kubectl" && sudo chmod +x /usr/local/bin/kubectl

      #   # Verify kubectl installation
      # - run:
      #     name: Verify kubectl installation
      #     command: ls -l /usr/local/bin/kubectl

      # # Verify kubectl version
      # - run:
      #     name: Verify kubectl version
      #     command: kubectl version

      # Authenticate with EKS Cluster
      # - run:
      #     name: Authenticate with EKS Cluster
      #     command: |
      #       aws eks --region us-east-1 update-kubeconfig --name NodeApp
      # # Deploy to EKS Cluster
      # - run:
      #     name: Deploy to EKS Cluster
      #     command: |
      #       kubectl apply -f ../deployment.yaml
      #       kubectl apply -f ../service.yaml

workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - unit_test:
          requires:
            - build_and_push
      - Update_manifest:
          requires:
            - unit_test
